#!/bin/bash

REPO_ROOT=$(git rev-parse --show-toplevel)

pushd $REPO_ROOT

# Ensure all template tags are updated.
if [[ -x ./scripts/update-tags.py ]]; then
    ./scripts/update-tags.py && \
        git add templates/*
elif [[ -x ./submodules/quickstart-atlassian-services/scripts/update-tags.py ]]; then
    ./submodules/quickstart-atlassian-services/scripts/update-tags.py \
        && git add templates/*
fi

popd
